# Generated by Django 3.1.5 on 2021-01-15 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210115_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='가입일시'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='수정일시'),
        ),
        migrations.AlterModelTable(
            name='members',
            table=None,
        ),
    ]
